### ISSUE TITLE
diffusers.models.autoencoder_kl

### ISSUE THREAD

**Issue by SevenAntares** [StartHua/ComfyUI_Seg_VITON#10]
File "C:\IA\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\cldm\cldm.py", line 14, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
  File "C:\IA\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\ldm\models\diffusion\ddpm.py", line 26, in <module>
    from diffusers.models.autoencoder_kl import AutoencoderKLOutput
ModuleNotFoundError: No module named 'diffusers.models.autoencoder_kl'

**Comment by klossm** [comment]
Install the appropriate dependencies to fix
pip install diffusers==0.20.2  transformers==4.33.2

**Comment by SevenAntares** [comment]
> Install the appropriate dependencies to fix pip install diffusers==0.20.2 transformers==4.33.2

yes it seems like that was it

**Comment by denwade-05** [comment]
> Install the appropriate dependencies to fix pip install diffusers==0.20.2 transformers==4.33.2

Thanks. 
After successfully uninstalled diffusers-0.27.2, and pip install diffusers==0.20.2 
It works!
