### ISSUE TITLE
Is it possible to use another open-source project based on the same dataset?

### ISSUE THREAD

**Issue by jackdiy** [StartHua/ComfyUI_Seg_VITON#5]
Based on the one you are using "https://github.com/rlawjdghek/StableVITON," I found another new project open-sourced by a Korean research team: https://github.com/SHShim0513/SD-VITON
It seems that this project also uses the dataset from https://github.com/shadow2496/VITON-HD, but its checkpoint does not seem to require manual application.
However, I am not particularly familiar with these projects, so I am not sure if it is feasible.

**Comment by ClothingAI** [comment]
Hello @jackdiy , I am new to this repo. Where can I find a workflow example? Could you provide me one please? Also where is the checkpoint?
